### ISSUE TITLE
No permission

### ISSUE THREAD

**Issue by Krissy47** [Zandercraft/Zandercraft-Bot#6]
Hello! I've been using Zandercraft for a bit and its been really good! the only problem that I'm having is that there's times where it will tell me "You have no permission to run this command". is there any way to bypass this?

**Comment by ZandercraftGames** [comment]
Hello @Krissy47! I am sorry that you are having trouble with the bot. Just to confirm, you are the owner and creator of that server or have had the owner set an in-bot permission level for you?

**Comment by Krissy47** [comment]
Yes, in the server I've been trying to get it to work in, I'm an administrator.

**Comment by ZandercraftGames** [comment]
Okay... So from what I have gathered from this, you have a role with Administrator permissions, but are not the owner and have not had the owner setup an in-bot permission level for your role? Correct?

**Comment by Krissy47** [comment]
I had the owner of the server try to get the bot to join a voice channel/play music and it told them that they had no permission to. In the server that I created, only I was able to have the bot play music. Does that help at all?

**Comment by ZandercraftGames** [comment]
Yes... So basically the way the bot works, is it has a built-in permissions system using the `+setlevel` command. The "owner" of that server must not be the actual owner and only has owner rank because the permission system is bypassed only by the real owner of the server who has owner status through discord and also the person who has the power to delete the server or transfer ownership of the server. The real owner of the discord server needs to do `+setlevel <ping the user or role> <permission level on a scale from 1-10>`.

**Comment by ZandercraftGames** [comment]
The minimum requirement for basic music commands is 2 or 3. 3 or 4 is required in order to use the skip command.

**Comment by Krissy47** [comment]
Awesome. Thank you so much!

**Comment by ZandercraftGames** [comment]
No problem. If you ever have another question, feel free to ask. I will try to answer as quickly as possible.
